config/routes.rb
Rails.application.routes.draw do

  resources :employees_emails
  resources :reservations
  resources :reviews
  resources :abouts
  resources :employees
  devise_for :users
  #devise_for :users, :controllers => {:registrations => "registrations"}

  root 'home#home'

  get'contact', to: 'home#contact'
  post'request_contact', to: 'home#request_contact'
end

app/models/employees_email.rb
class EmployeesEmail < ApplicationRecord
  belongs_to :employee
  validates:email, presence:true
  validates:email, uniqueness:true
end

app/controllers/employees_emails_controller.rb
class EmployeesEmailsController < ApplicationController
  before_action :set_employees_email, only: [:show, :edit, :update, :destroy]

  # GET /employees_emails
  # GET /employees_emails.json
  def index
    @employees_emails = EmployeesEmail.all
  end

  # GET /employees_emails/1
  # GET /employees_emails/1.json
  def show
  end

  # GET /employees_emails/new
  def new
    @employees_email = EmployeesEmail.new
  end

  # GET /employees_emails/1/edit
  def edit
  end

  # POST /employees_emails
  # POST /employees_emails.json
  def create
    @employees_email = EmployeesEmail.new(employees_email_params)

    respond_to do |format|
      if @employees_email.save
        format.html { redirect_to @employees_email, notice: 'Employees email was successfully created.' }
        format.json { render :show, status: :created, location: @employees_email }
      else
        format.html { render :new }
        format.json { render json: @employees_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees_emails/1
  # PATCH/PUT /employees_emails/1.json
  def update
    respond_to do |format|
      if @employees_email.update(employees_email_params)
        format.html { redirect_to @employees_email, notice: 'Employees email was successfully updated.' }
        format.json { render :show, status: :ok, location: @employees_email }
      else
        format.html { render :edit }
        format.json { render json: @employees_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees_emails/1
  # DELETE /employees_emails/1.json
  def destroy
    @employees_email.destroy
    respond_to do |format|
      format.html { redirect_to employees_emails_url, notice: 'Employees email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employees_email
      @employees_email = EmployeesEmail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employees_email_params
      params.require(:employees_email).permit(:employee_id, :email)
    end
end

app/helpers/employees_emails_helper.rb
module EmployeesEmailsHelper
end

app/views/employees_emails/_form.html.haml
= form_for @employees_email do |f|
  - if @employees_email.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employees_email.errors.count, "error")} prohibited this employees_email from being saved:"
      %ul
        - @employees_email.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :employee
    = f.text_field :employee_id
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/employees_emails/edit.html.haml
%h1 Editing employees_email

= render 'form'

= link_to 'Show', @employees_email
\|
= link_to 'Back', employees_emails_path

app/views/employees_emails/index.html.haml
.container.theme-showcase{role: "main"}
  .jumbotron
    %h1 Listing Employee Emails
    %p All Employee Emails in one place.
  %table
    %thead
      %tr
        %th Email
        %th
        %th
        %th

    %tbody
      - @employees_emails.each do |employees_email|
        %tr
          %td= employees_email.email
          %td= link_to 'Show', employees_email
          %td= link_to 'Edit', edit_employees_email_path(employees_email)
          %td= link_to 'Destroy', employees_email, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'New Employees email', new_employees_email_path

app/views/employees_emails/new.html.haml
%h1 New employees_email

= render 'form'

= link_to 'Back', employees_emails_path

app/views/employees_emails/show.html.haml
%p#notice= notice

%p
  %b Employee ID:
  = @employees_email.employee
%p
  %b Email:
  = @employees_email.email

= link_to 'Edit', edit_employees_email_path(@employees_email)
\|
= link_to 'Back', employees_emails_path