config/routes.rb
Rails.application.routes.draw do

  resources :employees_emails
  resources :reservations
  resources :reviews
  resources :abouts
  resources :employees
  devise_for :users
  #devise_for :users, :controllers => {:registrations => "registrations"}

  root 'home#home'

  get'contact', to: 'home#contact'
  post'request_contact', to: 'home#request_contact'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :Name, presence:true
  validates :StartTime, presence:true
  validates :EndTime, presence:true

  belongs_to :user
  belongs_to :employee

  scope :user_reservations, ->(user) { where(['user_id= ?', user.id]) }
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.user_reservations(current_user)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :Name, :StartTime, :EndTime, :employee_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.haml
= form_for @reservation do |f|
  - if @reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      %ul
        - @reservation.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :Name
    = f.text_field :Name
  .field
    = f.label :StartTime
    = f.datetime_select :StartTime
  .field
    = f.label :EndTime
    = f.datetime_select :EndTime
  .field
    = f.label :'employee (1 = John, 2 = Jane, 3 = Jaden)'
    = f.text_field :employee_id
  .actions
    = f.submit 'Save'

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
.container.theme-showcase{role: "main"}
  .jumbotron
    %h1 Listing Reservations
    %p All your bookings in one place.

  %table
    %thead
      %tr

        %th Name
        %th Start Time
        %th End Time
        %th
        %th
        %th

    %tbody
      - @reservations.each do |reservation|
        %tr

          %td= reservation.Name
          %td= reservation.StartTime
          %td= reservation.EndTime

          %td= link_to 'Show', reservation

  %p To cancel your booking <a href='/contact'>Contact Us here</a>
  %br

  = link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', reservations_path

app/views/reservations/show.html.haml
.container.theme-showcase{role: "main"}
  .jumbotron
    %h1 Your Order
    %p All the little details, see you soon.

  %p#notice= notice

  %p
    %b Location:
    = '1 High Street, Guildford, Surrey'
  %p
    %b Name:
    = @reservation.Name
  %p
    %b Start Time:
    = @reservation.StartTime
  %p
    %b End Time:
    = @reservation.EndTime

  = link_to 'Edit', edit_reservation_path(@reservation)
  \|
  = link_to 'Back', reservations_path